inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rubycw
  - rubocop-thread_safety
